# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  pbr_config = debug

else ifeq ($(config),release)
  pbr_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := pbr

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

pbr:
ifneq (,$(pbr_config))
	@echo "==== Building pbr ($(pbr_config)) ===="
	@${MAKE} --no-print-directory -C . -f pbr.make config=$(pbr_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f pbr.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   pbr"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"